

-- tables
-- Table: DIAGNOZA
CREATE TABLE DIAGNOZA (
    ID integer  NOT NULL,
    PRACOWNIK_ID integer  NOT NULL,
    PACJENT_ID integer  NOT NULL,
    Nazwa_diagnozy varchar2(40)  NOT NULL,
    Opis_diagnozy varchar2(100)  NOT NULL,
    Data_diagnozy date  NOT NULL,
    CONSTRAINT DIAGNOZA_pk PRIMARY KEY (ID)
) ;

-- Table: LEKI
CREATE TABLE LEKI (
    ID integer  NOT NULL,
    Nazwa_leka varchar2(30)  NOT NULL,
    Opis_leka varchar2(100)  NOT NULL,
    CONSTRAINT LEKI_pk PRIMARY KEY (ID)
) ;

-- Table: LEKI_DIAGNOZY
CREATE TABLE LEKI_DIAGNOZY (
    LEKI_ID integer  NOT NULL,
    DIAGNOZA_ID integer  NOT NULL,
    Dawtowanie varchar2(20)  NOT NULL,
    CONSTRAINT LEKI_DIAGNOZY_pk PRIMARY KEY (LEKI_ID,DIAGNOZA_ID)
) ;

-- Table: OSOBA
CREATE TABLE OSOBA (
    ID integer  NOT NULL,
    Nazwisko varchar2(30)  NOT NULL,
    Imie varchar2(20)  NOT NULL,
    Imie_ojca varchar2(30)  NOT NULL,
    PESEL integer  NOT NULL,
    CONSTRAINT OSOBA_pk PRIMARY KEY (ID)
) ;

-- Table: PACJENT
CREATE TABLE PACJENT (
    ID integer  NOT NULL,
    OSOBA_ID integer  NOT NULL,
    Data_przyjecia_pacjenta date  NOT NULL,
    Data_wypisu_pacjenta date  NOT NULL,
    CONSTRAINT PACJENT_pk PRIMARY KEY (ID)
) ;

-- Table: PRACOWNIK
CREATE TABLE PRACOWNIK (
    ID integer  NOT NULL,
    OSOBA_ID integer  NOT NULL,
    STANOWISKO_ID integer  NOT NULL,
    Data_zatrudnienia date  NOT NULL,
    Data_zwolnienia date  NOT NULL,
    Telefon_kontaktowy number(12,0)  NOT NULL,
    CONSTRAINT PRACOWNIK_pk PRIMARY KEY (ID)
) ;

-- Table: STANOWISKO
CREATE TABLE STANOWISKO (
    ID integer  NOT NULL,
    Nazwa_stanowiska varchar2(30)  NOT NULL,
    Pensja number(6,2)  NOT NULL,
    CONSTRAINT STANOWISKO_pk PRIMARY KEY (ID)
) ;

-- foreign keys
-- Reference: DIAGNOZA_PACJENT (table: DIAGNOZA)
ALTER TABLE DIAGNOZA ADD CONSTRAINT DIAGNOZA_PACJENT
    FOREIGN KEY (PACJENT_ID)
    REFERENCES PACJENT (ID);

-- Reference: DIAGNOZA_PRACOWNIK (table: DIAGNOZA)
ALTER TABLE DIAGNOZA ADD CONSTRAINT DIAGNOZA_PRACOWNIK
    FOREIGN KEY (PRACOWNIK_ID)
    REFERENCES PRACOWNIK (ID);

-- Reference: HISTORIA_CHOROBY_OSOBA (table: PACJENT)
ALTER TABLE PACJENT ADD CONSTRAINT HISTORIA_CHOROBY_OSOBA
    FOREIGN KEY (OSOBA_ID)
    REFERENCES OSOBA (ID);

-- Reference: LEKI_DIAGNOZY_DIAGNOZA (table: LEKI_DIAGNOZY)
ALTER TABLE LEKI_DIAGNOZY ADD CONSTRAINT LEKI_DIAGNOZY_DIAGNOZA
    FOREIGN KEY (DIAGNOZA_ID)
    REFERENCES DIAGNOZA (ID);

-- Reference: LEKI_DIAGNOZY_LEKI (table: LEKI_DIAGNOZY)
ALTER TABLE LEKI_DIAGNOZY ADD CONSTRAINT LEKI_DIAGNOZY_LEKI
    FOREIGN KEY (LEKI_ID)
    REFERENCES LEKI (ID);

-- Reference: PRACOWNIK_OSOBA (table: PRACOWNIK)
ALTER TABLE PRACOWNIK ADD CONSTRAINT PRACOWNIK_OSOBA
    FOREIGN KEY (OSOBA_ID)
    REFERENCES OSOBA (ID);

-- Reference: PRACOWNIK_STANOWISKO (table: PRACOWNIK)
ALTER TABLE PRACOWNIK ADD CONSTRAINT PRACOWNIK_STANOWISKO
    FOREIGN KEY (STANOWISKO_ID)
    REFERENCES STANOWISKO (ID);

-- End of file.

